/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalCalendar: typeof import('./../src/components/cal-calendar.vue')['default']
    CalDragGhost: typeof import('./../src/components/internal/cal-drag-ghost.vue')['default']
    CalEventBar: typeof import('./../src/components/internal/cal-event-bar.vue')['default']
    CalListView: typeof import('./../src/components/internal/cal-list-view.vue')['default']
    CalMiniMonth: typeof import('./../src/components/cal-mini-month.vue')['default']
    CalMonthView: typeof import('./../src/components/internal/cal-month-view.vue')['default']
    CalTimeEvent: typeof import('./../src/components/internal/cal-time-event.vue')['default']
    CalTimeGrid: typeof import('./../src/components/internal/cal-time-grid.vue')['default']
    CalTooltip: typeof import('./../src/components/internal/cal-tooltip.vue')['default']
  }
}
